baseURL = "https://logan-lieou.github.io/Website/"
languageCode = "en-us"
title = "Logan's Personal Website"
theme = "showfolio"

[params]
  name = "Logan's Personal Website"
  description = "Fullstack Software Engineer"
  author = "Logan DN. DeRose"
  authorEmail = "logan.lieou@protonmail.com"
  authorImage = "circle_woman.png"
  autoDarkMode = true

  copyright = "Copyright © 2022 - Logan DN. DeRose · All rights reserved"
  favicon = "portrait.jpg"

[params.homepage]
  title = "Hello 👋 My Name is Logan"
  tagline = "Fullstack Software Engineer"
  description = "My goal as a software engineer and product manager is to help your project team maintain its best practice through technical innovation and good execution."
  contact = ""

[params.homepage.resume]
  skills = ["Java", "C++", "Web Design", "Web Development", "AI", "Python"]

[[params.homepage.resume.work]]
  name = "Leon Robotics Solutions"
  role = "Fullstack Software Engineer"
  duration = "August 2020 - Current"

[params.homepage.social]
  github = "https://github.com/logan-lieou"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

